// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmpcqjsrmrsjexnszzqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptcGNxanNybXJzamV4bnN6enFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTY4NTcsImV4cCI6MjA3MzI3Mjg1N30.W6xm8rzGrUlW4e-ln1QxbmatSxzIs8CdWh5R_3TQyDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});